version: '3.8'
services:
  product-service:
    build: ./backend/product-service
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/ecommerce

  order-service:
    build: ./backend/order-service
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/ecommerce

  user-service:
    build: ./backend/user-service
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/ecommerce

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service
      - user-service

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - product-service
      - order-service
      - user-service
      - frontend

